services:
  web:
    build: 
      context: .
      dockerfile: apps/web/Dockerfile
    ports: 
      - "5173:5173"
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build: 
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db: 
    image: postgis/postgis:17-3.5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

      
